### ISSUE TITLE
Setup Wizard doesn't work

### ISSUE THREAD

**Issue by Quallenauge** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#22]
When using a new installation, the setup wizard crashes all the time.
Logcat says:
```
01-17 23:21:54.027  6525  6525 I SetupWizard.SetupWizardActivity: DEVICE_PROVISIONED=false USER_SETUP_COMPLETE=false
01-17 23:21:54.040  6525  6525 E SetupWizard.WizardScript: Ill-formatted wizard_script: android.resource://org.lineageos.setupwizard/raw/wizard_script
01-17 23:21:54.040  6525  6525 E SetupWizard.WizardScript: WizardScript must define a firstAction
01-17 23:21:54.042  6525  6525 D AndroidRuntime: Shutting down VM
01-17 23:21:54.043  6525  6525 E AndroidRuntime: FATAL EXCEPTION: main
01-17 23:21:54.043  6525  6525 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 6525
01-17 23:21:54.043  6525  6525 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.setupwizard/com.google.android.setupwizard.SetupWizardActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.wizardmanager.WizardAction com.google.android.wizardmanager.WizardScript.getFirstAction()' on a null object reference
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-17 23:21:54.043  6525  6525 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.wizardmanager.WizardAction com.google.android.wizardmanager.WizardScript.getFirstAction()' on a null object reference
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at com.google.android.wizardmanager.WizardManager.runScript(WizardManager.java:198)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at com.google.android.wizardmanager.WizardManager.runScript(WizardManager.java:188)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at com.google.android.wizardmanager.WizardManager.runScript(WizardManager.java:183)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at com.google.android.setupwizard.SetupWizardActivity.onCreate(SetupWizardActivity.java:111)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6999)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6990)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
01-17 23:21:54.043  6525  6525 E AndroidRuntime:        ... 9 more
01-17 23:21:54.046   811  3615 W ActivityManager:   Force finishing activity com.google.android.setupwizard/.SetupWizardActivity
```

**Comment by vladimiroltean** [comment]
Since when does this happen? I don't see it.

**Comment by Quallenauge** [comment]
Did you had the lineage setup wizard or only the gapps setup wizard when setting up the tablet?
Maybe it's my fault....

**Comment by vladimiroltean** [comment]
My Feb 26 build works with both setup wizards. I will repeat the experiment with a fresh build.

**Comment by Quallenauge** [comment]
Works fine now with latest lineage / gms framework.
